const ACTIONS = {
    DISCOVER_MOVIE: Symbol('DISCOVER_MOVIE'),
    DISCOVER_MOVIE_SUCCESS: Symbol('DISCOVER_MOVIE_SUCCESS'),
    DISCOVER_MOVIE_FAIL: Symbol('DISCOVER_MOVIE_FAIL'),
    GET_MOVIE: Symbol('GET_MOVIE'),
    GET_MOVIE_FAIL: Symbol('GET_MOVIE_FAIL'),
    GET_MOVIE_SUCCESS: Symbol('GET_MOVIE_SUCCESS'),
    CHANGE_DRAWER_STATE: Symbol('CHANGE_DRAWER_STATE'),
    CHANGE_TITLE: Symbol('CHANGE_TITLE'),
    ADD_TO_FAVORITES: Symbol('ADD_TO_FAVORITES'),
    REMOVE_FROM_FAVORITES: Symbol('REMOVE_FROM_FAVORITES'),
    GET_TRAILER: Symbol('GET_TRAILER'),
    GET_TRAILER_SUCCESS: Symbol('GET_TRAILER_SUCCESS'),
    GET_TRAILER_FAIL: Symbol('GET_TRAILER_FAIL'),
    SEARCH_MOVIE: Symbol('SEARCH_MOVIE'),
    SEARCH_MOVIE_SUCCESS: Symbol('SEARCH_MOVIE_SUCCESS'),
    SEARCH_MOVIE_FAIL: Symbol('SEARCH_MOVIE_FAIL')
}

export default ACTIONS;