const ACTIONS = {
    DISCOVER_MOVIE: Symbol('DISCOVER_MOVIE'),
    DISCOVER_MOVIE_SUCCESS: Symbol('DISCOVER_MOVIE_SUCCESS'),
    DISCOVER_MOVIE_FAIL: Symbol('DISCOVER_MOVIE_FAIL')
}

export default ACTIONS;