const ACTIONS = {
    DISCOVER_MOVIE: Symbol('DISCOVER_MOVIE'),
    DISCOVER_MOVIE_SUCCESS: Symbol('DISCOVER_MOVIE_SUCCESS'),
    DISCOVER_MOVIE_FAIL: Symbol('DISCOVER_MOVIE_FAIL'),
    GET_MOVIE: Symbol('GET_MOVIE'),
    GET_MOVIE_FAIL: Symbol('GET_MOVIE_FAIL'),
    GET_MOVIE_SUCCESS: Symbol('GET_MOVIE_SUCCESS'),
    CHANGE_DRAWER_STATE: Symbol('CHANGE_DRAWER_STATE'),
    CHANGE_TITLE: Symbol('CHANGE_TITLE')
}

export default ACTIONS;